#!/bin/bash

sets=0
metrics="1 2 3 4 5 6 7 8 9"
declare -a spots
declare -a users=(p1 p2)
declare -a b=(. . . . . . . . . .)
declare -a ids=(o x)

usage()
{
cat<<_EOF_

	Tic Tac Toe Game!
        
	# board design
	#  1 | 2 | 3
	#  --------
	#  4 | 5 | 6
	#  --------
	#  7 | 8 | 9

_EOF_
}

time_to_exit()
{
  echo -e "\n\nGood Bye.\n"
  exit 1
}

board()
{
cat <<_EOF_
     [SET-$sets]
====================
    ${b[1]} | ${b[2]} | ${b[3]}
    ---------
    ${b[4]} | ${b[5]} | ${b[6]}
    ---------
    ${b[7]} | ${b[8]} | ${b[9]}
_EOF_
}

get_my_move()
{
# random move.
  if [[ $moved -eq 0 ]]; then
    spot=$(shuf -e ${spots} -n 1)
    is_spot_free $spot
  fi
}

is_spot_free()
{
  local s=$1
  if [ "${b[$s]}" = '.' ]; then
    spot=$1
    b[$spot]=$c
    echo -e "\n[c]($c) has chosen spot $spot"
    ((moved+=1))   
  fi
}

# computer
can_win()
{
  local w=$1
  local a
  
  winsets=(147 123 159 258 369 789 456 357)
  for a in ${winsets[@]}; do
#    for w in $c $p1; do
      one="${a:0:1}"
      two="${a:1:1}"
      three="${a:2:1}"
      if [[ $moved -eq 0 ]]; then
        if [[ ${b[$one]} = "$w" ]] && [[ ${b[$two]} = "$w" ]]; then
          is_spot_free $three
        elif [[ ${b[$one]} = "$w" ]] && [[ ${b[$three]} = "$w" ]]; then
          is_spot_free $two
        elif [[ ${b[$two]} = "$w" ]] && [[ ${b[$three]} = "$w" ]]; then
          is_spot_free $one
        fi
      fi
#    done
  done
}

# get empty spots on board
get_empty_sets()
{
 spots=""
 for i in {1..9}; do
   if [[ ${b[$i]} = "." ]]; then
     spots="$spots $i"
   fi
     nspots=${spots// /}
 done
     spots=${spots/ /}
}

# simple logic to get winner
get_winner()
{
  local i=$1	# user
  local v=0	# wining score    

    if [[ "${b[1]}" = "${!i}" ]] && [[ ${b[2]} = "${!i}" ]] && [[ ${b[3]} = "${!i}" ]]; then
      ((v+=1))  
    elif [[ "${b[1]}" = "${!i}" ]] && [[ ${b[4]} = "${!i}" ]] && [[ ${b[7]} = "${!i}" ]]; then
      ((v+=1))  
    elif [[ "${b[1]}" = "${!i}" ]] && [[ ${b[5]} = "${!i}" ]] && [[ ${b[9]} = "${!i}" ]]; then
      ((v+=1))  
    elif [[ "${b[2]}" = "${!i}" ]] && [[ ${b[5]} = "${!i}" ]] && [[ ${b[8]} = "${!i}" ]]; then
      ((v+=1))  
    elif [[ "${b[3]}" = "${!i}" ]] && [[ ${b[6]} = "${!i}" ]] && [[ ${b[9]} = "${!i}" ]]; then
      ((v+=1))  
    elif [[ "${b[3]}" = "${!i}" ]] && [[ ${b[5]} = "${!i}" ]] && [[ ${b[7]} = "${!i}" ]]; then
      ((v+=1))  
    elif [[ "${b[4]}" = "${!i}" ]] && [[ ${b[5]} = "${!i}" ]] && [[ ${b[6]} = "${!i}" ]]; then
      ((v+=1))  
    elif [[ "${b[7]}" = "${!i}" ]] && [[ ${b[8]} = "${!i}" ]] && [[ ${b[9]} = "${!i}" ]]; then
      ((v+=1))  
    fi

  if [[ "$i" = 'p1' ]]; then
      v1=$v
      w1=$((c1 + v))
  else
      v2=$v
      w2=$((c2 + v))
  fi

cat<<_EOF_

     -SCORE-
    ---------
    | P1| P2|
    ---------
    |  ${w1:-0}|  ${w2:-0}|
    ---------

_EOF_

if [[ ${v1} -gt ${v2} ]]; then
  echo -e "\nPlayer 1 won by [${w1:-0}-${w2:-0}] in $sets sets.\n"
  break
elif [[ ${v1} -lt ${v2} ]]; then
  echo -e "\nPlayer 2 won by [${w1:-0}-${w2:-0}] in $sets sets.\n"
  break
fi
}

register_player()
{
local yn
while true; do
  read -p "Do you want to play with computer? [y/n] " yn
  case $yn in
  [Yy] ) r=$(shuf -i 0-1 -n 1)
         users[1]=c
         player=${users[$r]}
         if [ "$player" = 'p1' ]; then
           echo -e "\np1 will choose first."
           read -p "player ID for p1 [${ids[0]}/${ids[1]}]: " p1
         else
           echo -e "\ncomputer[$player] will choose first: \c"
           c=$(shuf -i 0-1 -n 1); c=${ids[$c]}
           echo -n "$c"
         fi
         break;;
  [Nn] ) r=$(shuf -i 0-1 -n 1)
         player=${users[$r]}
         read -p "player ID for ${player} [${ids[0]}/${ids[1]}]: " ${player}
         break;;
   * )   echo -e "choose y or n.";;
  esac
done

    if [[ "$player" = "p1" ]] && [[ "${users[1]}" = "p2" ]]; then
      if [[ -z "$p1" ]] || [[ "$p1" != "x" ]] && [[ "$p1" != "o" ]]; then
        echo -e "player ID should be o or x."
        exit 1
      elif [[ "$p1" = 'o' ]]; then
        p2=x
      elif [[ "$p1" = 'x' ]]; then
        p2=o
      fi
    elif [[ "$player" = 'c' ]]; then
      if [[ "$c" = 'o' ]]; then
        p1=x
      else
        p1=o
      fi
    elif [[ "${player}" = "p2" ]]; then
      if [[ -z "$p2" ]] || [[ "$p2" != "x" ]] && [[ "$p2" != "o" ]]; then
        echo -e "player ID should be o or x."
        exit 1
      elif [[ "$p2" = 'o' ]]; then
        p1=x
      else
        p1=o
      fi
    else
      if [[ "$p1" = 'o' ]]; then
        c=x
      elif [[ "$p1" = 'x' ]]; then
        c=o
      else
        echo -e "player ID should be o or x."
        exit 1
      fi
    fi

    printf '\n%s\n%s\n' "${users[0]} : $p1" "${users[1]} : ${p2:-$c}"
}

play()
{
  local u=$r
  ((sets+=1))
  get_empty_sets
  while [ ${#nspots} -ge 1 ]; do
    moved=0
    case $u in
      0 ) player=${users[0]}
          get_empty_sets
          if [ ${#nspots} -lt 1 ]; then
            break
          fi
          while true; do
            read -p "[${player}](${!player}) choose your spot [${nspots}]: " spot
            if [[ "${b[$spot]}" = '.' ]] && [[ ! -z $spot ]] && [[ ! $spot -gt 9 ]] && [[ ! "$spot" =~ [a-z] ]]; then
              if [ "$player" = "p1" ]; then
                b[$spot]=${p1}
              fi
              break
            else
              echo -e "That spot is not allowed."
            fi
          done
          board
          get_winner p1
          u=1;;
      1 ) player=${users[1]}
          get_empty_sets
          if [ ${#nspots} -lt 1 ]; then
            break
          fi
          if [ "${users[1]}" = "p2" ]; then
            while true; do
              read -p "[${player}](${!player}) choose your spot [${nspots}]: " spot
              if [[ "${b[$spot]}" = '.' ]] && [[ ! -z $spot ]] && [[ ! $spot -gt 9 ]] && [[ ! "$spot" =~ [a-z] ]]; then
                b[$spot]=$p2
              break
              else
                echo -e "That spot is not allowed."
              fi
            done
            board
            get_winner p2
          else
            # logic for computer move
            can_win $c
            can_win $p1
            # is still not moved
            get_my_move
            board	# print board only once in a 1 player game.
            get_winner c
          fi
          u=0;;
    esac
  done
}

### main ###
trap time_to_exit INT

usage
register_player
play

while true; do
  read -p 'Do you want to play again? [y/n] ' yn
  case $yn in
    [Yy]) b=(. . . . . . . . . .)
          c1=${w1:-0}
          c2=${w2:-0}
          play;;
    [Nn]) echo -e "\nGood Bye.\n"
          exit 0;;
  esac 
done
